spring:
  application:
    name: Diet
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    #        default_batch_fetch_size: 100 // 이거와 태그의 관계 공부.
    open-in-view: true

cloud:
  aws:
    s3:
      bucket: dohealthy-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${IAM_ACCESS_KEY}
      secret-key: ${IAM_SECRET_KEY}


springdoc:
  packages-to-scan: gangdong.diet.domain
  default-consumes-media-type: application/json;
  default-produces-media-type: application/json;
  show-actuator: true
  swagger-ui:
    path: /api/docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    default-model-expand-depth: 2
